### ISSUE TITLE
deploy script/process

### ISSUE THREAD

**Issue by adamrneary** [activecell/activecell.com#1] opened 2012-04-16 17:53 UTC
I would like to build a deployment script to take over where Jekyll stops. Jekyll delivers a _site directory with 100% static assets generated based on templates. But the assets are still raw. 

On commit to the repo, Jekyll should generate a new _site directory via Jekyll, and our script/process should then automatically do the following:
1. generate (or clear out) a _deploy folder 
2. concatenate, minify, compress, and timestamp CSS files, replacing tags in html requesting the raw documents
3. concatenate, minify, precompile, compress, and timestamp JS files, replacing tags in html requesting the raw documents
4. update html to include expires headers for all assets
5. copy over updated assets to _deploy folder (along with images, etc.)
6. sync to S3/Cloudfront, expiring any caches as appropriate
7. remove any updated assets from S3/Cloudfront as part of the sync

Provided we have a jekyll-powered site, a commit to the git repo should flow all the way to deployed site and CDN automatically.
If someone were to use this script/process without jekyll, a commit to the git repo should nonetheless flow all the way to deployed site and CDN automatically based on the static site in the repo.

Quick note on S3 for our particular implementation: As of today we are hosting the HTML itself for profitably.com on github pages (profitably.github.com), and my hope is to leave HTML on github pages but move CSS/JS/image assets to CDN. Ideally we would be able to toggle that feature so that if we wanted HTML on the CDN we could do that.

**Comment by umarsheikh** [comment] 2012-04-17 11:42
i have to take off early today to show my son to a doctor. will be resuming from tomorrow.

there are some plugins to do compression for a jekyll-generated site, will look at those to see if they do what we need.

if we really decide that we want to serve the assets from another site, example our CDN, why do we need to do compression?

**Comment by adamrneary** [comment] 2012-04-17 13:54
Umar--totally understand the kid factor. I have a 6.5 month old at home. :-)

Since the jekyll generator creates a plain vanilla static site, any plugins we use don't necessarily have to be jekyll-related. Why don't we use the Google Closure Compilier on the concatenated js files for minification and then just gzip for compression (unless you found a better plugin?). To get it done, maybe something like https://github.com/jlecomte/smasher ?

What do you think?

**Comment by umarsheikh** [comment] 2012-04-17 15:27
Wow? I have a 6-month old at home, exactly to date! 17 October!

Can you send me any post-receive hooks, or your current deployment procedure, so i can build on top of it. That way, i might be able to avoid redoing what we dont need.

I can look at the link you sent nevertheless, but it was last worked on 3 years ago. Still, if it does its job well, we can use it.

**Comment by umarsheikh** [comment] 2012-04-17 16:46
I still do not have the current deployment related files, and I am waiting for them; if they are not necessary we can ignore those.
First: on using the google closure compiler

You said: Why don't we use the Google Closure Compilier on the concatenated js files for minification
If we already have minification, then using the google closure compiler is a snap. I downloaded a prebuilt compiler jar file from http://code.google.com/p/closure-compiler/downloads/list (the first link, http://code.google.com/p/closure-compiler/downloads/detail?name=compiler-20120305.zip&can=2&q=) which give you a compiler.jar file. Once we install this on the server, we can run:
java -jar compiler.jar --js=path/to/_site/assets/js/application.js --js_output_file=/another/path/to/out.js

even if we dont have one file, we can still compress a number of files by running the above command for each one.

Should i go ahead and write a ruby script that does the following:

output_path = /path/to/final/file
for each .js file x in a directory d # (example _site)
`java -jar compiler.jar --js=#{x} --js_output_file=#{outputpath}/x`
end

Second: I also found this: https://github.com/moshen/jekyll-asset_bundler
I am still exploring it, but it might just do the compression/minification etc on both css and javascript for us! it is looking promising.

**Comment by umarsheikh** [comment] 2012-04-17 17:07
as a first step, would a ruby or a shell script that does the following be all right:

for each file in _site in a recursive way
  if file is an image, or an html file, copy it over to the same path in _deploy
  if file is a js or a css file, minify and copy over to the sampe path in _deploy
end

that will accomplish minification for us.

I dont understand which files we need to compress. by compression, you mean generating a tgz or a zip file from it? do you want to compres the whole _deploy folder, or some files in it?

**Comment by adamrneary** [comment] 2012-04-17 17:24
I didn't realize jekyll had plug-ins like that. The jammit one (https://gist.github.com/1224971 with config at http://documentcloud.github.com/jammit/) will work best from what i can see if you think you could get the configuration down.

Package, compress, and gzip all default to "yes" so it is doing what we need from that standpoint. For javascript compressor let's just use the default yui option.

Sound good?

Also, to your deployment related files, we literally have nothing. Because we're using github pages, when I commit to the repo, it's immediately made available on profitably.github.com. Does that make sense? 

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by adamrneary** [comment] 2012-04-17 17:27
Also--the jammit plugin should get us to 1 css file and 1 js file. At that point we still need to get those files and the image files onto a CDN correctly...

(Just making sure we thinking about what steps the plugin takes care of for us vs what we still need to do!)

**Comment by umarsheikh** [comment] 2012-04-18 12:52
I have explored jekyll and its plugins a bit today. i have found out the following:
- i am working on adding a javascript compressor plugin that you sent, at https://gist.github.com/2384637 . i have figured out how to generate one js file so far which is compressed ,and also the .tgz file, i am now testing if we use the same approach for css or not.

Even if the jammit generator does the following:
- compress, minify, and concatenate js
- compress minify and concatenate css

we will still have the issue that github does not run plugin code. I have read something to this effect on one of the sites, and i will verify to see if that is correct or not.

if this is correct, i think our best bet is to do the following:
- run jekyll --server locally so that the compressed files are outputted. we then will have to copy them over from the _site directory to the assets folder, commit them, and push them, so that our site can server one file.

we will also have to replace all js includes with one include, that of the generated js file, same is the case with the css files.

i am going to push some changes to another branch, where you can inspect the changes.

i have also created my own umarsheikh.github.com github pages, so far it is just using github pages, i am experimenting wtih jekyll there to figure out stuff!

**Comment by adamrneary** [comment] 2012-04-18 12:56
Sounds good, and thanks for being so diligent. At the end of the day, if we have a deploy script we can locally run that will process those steps we're in good shape.

I am not sure about what's required for the CDN integration, but it may be the case that we have to replace the "includes" with references to the S3 versions anyway. Something to think about.

Appreciate the progress... 

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-18 14:24
one question: one pre-requisite of having one css and one js file (ignoring the ie7-type files for now) is that all the js files should be included in the header.html or the index.html, and we should remove any js/css includes from all other pages, is that right? i will then have to do this processing on the *.html files as well.

**Comment by umarsheikh** [comment] 2012-04-18 14:33
i couldnt push to a second branch i created in the profitably.github.com directory, so i am forced to push to profitably.github.com

**Comment by adamrneary** [comment] 2012-04-18 14:36
hmm. if it doesn't let you, just shoot me a pull request and I should be able to work off that.

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-18 14:44
ah, i see. i dont have write access to it, so i need to do a pull request. as the work is not yet complete, i dont know if i should do a pull request now or not. the repository with teh changes is at: https://github.com/umarsheikh/profitably.github.com you can see the latest changes.

I will be doign a pull request nevertheless to make it easy to inspect changes, you can always delay teh actual merge when we have made more progress.

**Comment by adamrneary** [comment] 2012-04-18 14:48
Absolutely.

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by adamrneary** [comment] 2012-04-19 22:06
Just merged that last pull request and it threw all sorts of errors when pushed out to master, so I quickly reverted back to the stable prior case. Once we're farther along we'll have to find a smarter way to test this. How is it coming? Are we going to be able to wrap this component pretty soon?

**Comment by adamrneary** [comment] 2012-04-19 22:08
To the testing question, I think once we're pushing all non-html assets to s3 as part of the deploy, we'll be able to pull changes into a local branch and test just the same as if it was on the server. So let's get that s3 component in place, and I think we'll have little trouble testing...

**Comment by umarsheikh** [comment] 2012-04-20 13:08
regarding your earlier, comment...
first, this task is still not complete, i opened the pull request so that you can see the changes, not try to merge it in now. i will be adding more updates, and when done, i will let you know.
second, there is one problem with how it works with jekyll plugins now. My point is, previously you just made commits, and when you pushed, it was deployed. but we need to now run plugins to compress assets, and this code now works which concatenates and compresses assets. but the problem is, when you do a git push, currently git does not run the plugin code as it is in safe mode, so these assets will not compile, and you may get errors. ithink you were getting errors when it failed to compile assets?
so what i foresee is that once we are ready to push, we need to do the following:
1) jekyll --server. this will generate compiled.js file, and all.css file in the assets directory.
2) commit these two files, and push. but we need to push such that the plugin code does not run on github. may be there is a setting for that?
3) now the code will be updated and we are done.

i will now work on the s3 component. but i dont completely understand this task. can you explain this a bit more?

**Comment by umarsheikh** [comment] 2012-04-20 13:21
One comment, i landed up on this page, http://code.lancepollard.com/github-as-a-cdn/ and it says that github pages automatically compresses using gzip, so the gzipping problem is automatically solved. (read the first three lines in the "Github Pages Solves the Asset Optimization Problem" section)

**Comment by adamrneary** [comment] 2012-04-20 13:25
Absolutely understood.

The goal with the S3/Cloudfront/CDN question was to be able to get out assets out to a CDN where they are delivered more consistently/professionally than we can count on from Github pages, which is good for project pages and so on but might not be reliable as a high-traffic, primary marketing site.

Now, my original vision was to leave the HTML on github pages and serve images/css/js from S3, but it sounds like now you can very easily host the entire thing there. Articles like http://s3tools.org/s3cmd-sync and talk about it. Plus, there's this: https://github.com/versapay/jekyll-s3.

So you're absolutely right that when we have a change made we'll need to run jekyll --server or whatever to get the compression done. What I wonder is, can we implement jekyll-s3 and just run the jekyll-s3 command to get the assets compiled and run through jammit (which does the gzip, too!) and then synced with S3?

Then I could just commit the change to github and be done. What do you think?

**Comment by umarsheikh** [comment] 2012-04-20 13:33
also, if you already have a s3 account, then the instructions here are of any help? http://www.maxmasnick.com/2012/01/21/jekyll_s3_cloudfront/ it is about how jekyll-powered site can be deployed on s3.

**Comment by adamrneary** [comment] 2012-04-20 13:35
http://www.maxmasnick.com/2012/01/21/jekyll_s3_cloudfront/ Great article.

**Comment by adamrneary** [comment] 2012-04-20 13:40
How funny that we just sent each other the same article. His publish.sh sounds like it does all the work. If we can get something like that which includes the jekyll-server and jammit stuff, we're golden.

Yes, I have created the bucket will send details through oDesk.

**Comment by adamrneary** [comment] 2012-04-20 13:50
also, i've created a branch called "deploy_update" so that we can pull updates in there without any worry about impact on the live. once we're tested on s3/cloudfront i will merge to master.

**Comment by umarsheikh** [comment] 2012-04-20 16:48
sent u a message on odesk. there is a jekyll-s3 gem there, we can add details to it and lookslike we are done!

**Comment by umarsheikh** [comment] 2012-04-20 17:13
i see, we both talked of jekyll-s3 wihtout reading each other completely!

First, some clarification is needed: once we deploy on s3, we dont need to also host it in github pages, is that correct?

if that is correct, all we want to do is to deploy this site, or at least the assets on s3. if that is correct, then it does look like all we need to do is add the jekyll-s3 gem, create a bucket on s3, add teh details of the access key and buckets etc to the yml file used by jekyll-s3, execute the command jekyll-s3 on the command line, and we have our deployment.

**Comment by adamrneary** [comment] 2012-04-20 17:17
First--correct. We don't need to host on github pages. I will repoint the dns to cloudfront, and we can use profitably.github.com as a free/automatic staging env.

Second--correct. Let's do it. I think we still need the jammit stuff for the asset pipeline, but then jekyll-s3 should take care of the rest. Can you test it out with the credentials i provided? I think we're probably 99% there... 

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-20 17:27
it feels so good i am in the middle of a deploy right now!!!

On Fri, Apr 20, 2012 at 10:17 PM, Adam Neary <
reply@reply.github.com

**Comment by umarsheikh** [comment] 2012-04-20 17:39
i just did a deploy using jekyll-s3 and you can see the site up and running
at http://www.myveryprofitably.com.s3.amazonaws.com/index.html

So this task looks quite done!

The deployment is a two-step process:
1 jekyll --server to generate the _site folder
2 jekyll-s3 to deploy on s3

**Comment by adamrneary** [comment] 2012-04-20 17:41
It seems like it's missing a handful of assets. Are you seeing that if you inspect?

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-20 17:44
yes, some 6 assets, andthey are pointing to a path on my local machine! i am deploying again after some cleaning up, i think i may have to adjust some paths and we should be fine then

**Comment by adamrneary** [comment] 2012-04-20 17:47
Cool. Also, I think you should be able to point ALL assets to the cloudfront versions rather than the s3 versions so that it takes advantage of the CDN capabilities.

Max's article (http://www.maxmasnick.com/2012/01/21/jekyll_s3_cloudfront/) talks about taking care of that with a liquid template. Whatever's easiest. Like you said, we're almost done, and it would be great to wrap this up and put a bow on it.

Great job--almost there!
-A

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-20 17:53
the reason there are some missing assets is that some of the paths are like: ../img/... whatever, and they are getting expanded into absolute paths on my machine. we will need to visit all paths on the site and correct them to make them work

**Comment by umarsheikh** [comment] 2012-04-20 17:56
so i need to simply log into s3, create a cloudfront for the bucket and we are done? for that, i will need to have the login for the amazon account, i dont have the one for profitably.

**Comment by adamrneary** [comment] 2012-04-20 17:59
I already added one and provided the details in the last odes message. i believe, however, the html needs to be pointing to the cloudfront url rather than the s3 url, which is where the liquid template (or some other basic/automated mechanism comes into play).

If you deploy the site to http://www.profitably.com.s3-website-us-east-1.amazonaws.com/ rather than http://www.myveryprofitably.com.s3.amazonaws.com/index.html we should see the same assets repopulated to d2h0dyinjrpfzl.cloudfront.net automatically. 

does that make sense? 

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-20 18:00
no, we need to create the liquid filter, and for each asset we want served from cloudfront, we need to pass it through this filter. so we will need to inspect all assets and add the liquid filter to each one of them. we can do that once we have the details of the cloudfront, and for that, you can give me credentials, or you can log in, create it and we can then use it.

**Comment by adamrneary** [comment] 2012-04-20 18:02
Exactly. Again, I've already created the cloudfront instance and sent over all the details. Which settings are you missing?

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-20 18:46
i have added the filter and corrected the bucket url and pushed. i still need to figure out how to actually make this filter fire! it is getting late for home (there will probably be no lights at 12 midnight for an hour so i need to reach homre before that!)

I now just need to adjust urls like so:

instead of  < link href = " /assets/all.css "  rel="stylesheet" >
something like: < link href = "{{ '/assets/all.css | cdn }} "  rel="stylesheet"  >
but it is apparently not working like that.
i still need to figure out how to make this filter work by hacking into the above line! i can attempt to do that either tomorrow or monday, and then we can replicate the above line on all asset requires.

**Comment by adamrneary** [comment] 2012-04-20 18:49
Cool. Hit me with a pull request for everything you've got and I can
take a look this weekend potentially...?

Sent from my iPhone

On Apr 20, 2012, at 2:46 PM, umar
reply@reply.github.com
wrote:

**Comment by umarsheikh** [comment] 2012-04-23 12:10
Hi
I just finished the last change, which was to make < link href = "{{ '/assets/all.css | cdn }} " rel="stylesheet" >-type changes work. They are working now! Also, I corrected quite a number of urls in the profitably.css file, so that they are also now working. i just deployed some changes are http://www.profitably.com.s3-website-us-east-1.amazonaws.com.s3.amazonaws.com/index.html so you can take a look there.

There are three tasks left still:
1) inspect the whole site, and correct all urls of the type: url ( ../img/someimg.png) to url (/assets/img/someimg.png)
2) concatenate more javascript files together. all would be best. similarly concatenate all css files as well so there is just one javascript and just one css file
3) we need to figure out the correct details for the contents in the _config.yml and the _jekyll_s3.yml files, especially with relation to the s3 bucket name, and the cdn. Also, even though the asset url stands corrected, so that if you inspect the page at http://www.profitably.com.s3-website-us-east-1.amazonaws.com.s3.amazonaws.com/index.html you will see that it requires < link rel="stylesheet" href="http://d2h0dyinjrpfzl.cloudfront.net/assets/all.css " > as it should, there is no css file at the url. this means that we have something missing either in our configuration, or that the cdn url is not correct, or the cdn is not working. we need to correct this detail. can you see exactly which bucket maps to which cdn? and can you open up a cdn url to make sure it works? you said that the cdn http://d2h0dyinjrpfzl.cloudfront.net should map to www.profitably.com.s3-website-us-east-1.amazonaws.com, which implies that if we deploy to www.profitably.com.s3-website-us-east-1.amazonaws.com then the site should also be accessible at http://d2h0dyinjrpfzl.cloudfront.net/index.html but that is currently not the case.

so once we figure the exact cdn url, the exact bucket url, we should be good.

I am now working on concatenating all css and js files now.

**Comment by adamrneary** [comment] 2012-04-23 12:32
Cool. Shoot me a pull request for what we have so far please?

Sent from my awesome iPhone

On Apr 23, 2012, at 8:10 AM, umar
reply@reply.github.com
wrote:

**Comment by umarsheikh** [comment] 2012-04-23 12:43
the pull request is there, https://github.com/profitably/profitably.github.com/pull/4/commits the last commit is 8d26efd5 "now the url rewriting of cdn works, still to correct cdn path though"

**Comment by adamrneary** [comment] 2012-04-23 12:48
So it is! My fault! :-)

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by umarsheikh** [comment] 2012-04-23 13:31
there are three html pages only in the site there, i have combined all their javascripts now, and their css files as well. there are quit a number of javascript and two css files that are not being referenced, which are not combined as of yet.

I think this task is now more or less done. we now only need the configuration changes to make assets work out of cdn. once that is done, i can replace the code:

< script type="text/javascript" src="/assets/compiled.js">< / script>
with 
< script type="text/javascript" src="{{ '/assets/compiled.js' | cdn }} ">< / script>
(three places in total)
and similarly remove duplicate lines in the case of the assets/all.css files, and we should be done

also, update again before accepting the pull request.

**Comment by adamrneary** [comment] 2012-04-23 13:43
Sounds good. I will hack on this a bit this morning and see if I can fill in any gaps, but I agree it's essentially complete. if you've got some other projects to sort out, go ahead and take a look at those until I get back to you? We've got a ton of additional work to do, but I will need to sort out which to start on first!

Thanks again--great work.

**Comment by umarsheikh** [comment] 2012-04-23 13:59
Sure!!!

On Mon, Apr 23, 2012 at 6:43 PM, Adam Neary <
reply@reply.github.com

**Closed as completed** 2012-04-23 16:04 UTC
Labels: enhancement
